---
resources:
- name: book-producer
  type: git
  source:
    uri: https://github.com/gfoster-pivotal/talks.git
- name: catalog-consumer
  type: git
  source:
    uri: https://github.com/gfoster-pivotal/talks.git
- name: catalog-consumer-previous
  type: git
  source:
    uri: https://github.com/gfoster-pivotal/talks.git


jobs:
- name: book-producer
  public: true
  plan:
  - get: book-producer
    trigger: true
  - task: build-book-producer
    file: book-producer/core-practices/how-to-pair/pairing-demo/concourse/build-book-producer.yml

- name: catalog-consumer-previous
  public: true
  plan:
    - get: catalog-consumer
      version:
        ref: c2bbc20b82d52e002fc060bec438958679f31761
    - get: book-producer
      passed: [book-producer]
      trigger: true
    - task: build-catalog-consumer
      file: catalog-consumer/core-practices/how-to-pair/pairing-demo/concourse/build-catalog-consumer.yml

#- name: catalog-consumer-current
#  public: true
#  plan:
#    - get: pairing-demo
#      passed: [book-producer]
#      trigger: true
#    - task: build-catalog-consumer
#      file: pairing-demo/core-practices/how-to-pair/pairing-demo/concourse/build-catalog-consumer.yml
